/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define CALCPROG 0x30090949
#define CALCVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  int * add_1(int *, CLIENT *);
extern  int * add_1_svc(int *, struct svc_req *);
#define MUL 2
extern  int * mul_1(int *, CLIENT *);
extern  int * mul_1_svc(int *, struct svc_req *);
#define INIT 3
extern  void * init_1(int *, CLIENT *);
extern  void * init_1_svc(int *, struct svc_req *);
extern int calcprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  int * add_1();
extern  int * add_1_svc();
#define MUL 2
extern  int * mul_1();
extern  int * mul_1_svc();
#define INIT 3
extern  void * init_1();
extern  void * init_1_svc();
extern int calcprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
